### ISSUE TITLE
Using RandomForestQuantileRegressor model for uncertainty quantification

### ISSUE THREAD

**Issue by jmaddalena** [zillow/quantile-forest#42]
I can see how this package can be used to generate predictions for the mean, median, or any given quantile. I am interested in using quantile random forests to get an empirical distribution of predicted values that represent the model uncertainty for a new sample. This can be done in R's ranger by taking a large enough sample, with replacement, using the `what` argument during the predict call:

`pred <- predict(rf, mtcars[27:32, ], type = "quantiles", what = function(x) sample(x, 1000, replace = TRUE))`

This provides an empirical distribution of the prediction distribution. Then, if you want a single number representing uncertainty of your prediction, you can take the standard deviation of these values.

I saw a similar issue [here](https://github.com/zillow/quantile-forest/issues/19) where someone was asking how to do something like this but I wasn't 100% sure that was the same thing that I am looking for. Thank you for any clarification you can provide.

**Comment by reidjohnson** [comment]
Hi Julia, thanks for the question!

The example you provided of the functionality available in R with ranger is helpful. So while this package doesn't currently provide a convenience function similar to the level in ranger, it is possible to extract the proximities (essentially the empirical distribution) used to calculate the quantiles and instead apply any function of interest, similar to the issue you noted.

Here's an example with a convenience function that allows you to pass a user-specified function similar to ranger:

```python
import numpy as np
from quantile_forest import RandomForestQuantileRegressor
from sklearn import datasets
from sklearn.model_selection import train_test_split


def predict(reg, X, quantiles=0.5, what=None):
    """Custom prediction method that allows user-specified function.

    Parameters
    ----------
    reg : BaseForestQuantileRegressor
        Quantile forest model object.
    X : array-like, of shape (n_samples, n_features)
        New test data.
    quantiles : float or list of floats, default=0.5
        Scalar or vector of quantiles for quantile prediction.
    what : Any, optional
        User-specified function for prediction used instead of quantiles.
        Must return a numeric vector.

    Returns
    -------
    Output array with the user-specified function applied (if any).
    """
    if what is None:
        return reg.predict(X, quantiles=quantiles)

    # Get the complete set of proximities for each sample.
    proximities = reg.proximity_counts(X)

    # Retrieve the unsorted training responses from the model (stored in sorted order).
    reverse_sorter = np.argsort(reg.sorter_, axis=0)
    y_train = np.empty_like(reg.forest_.y_train).T
    for i in range(y_train.shape[1]):
        y_train[:, i] = np.asarray(reg.forest_.y_train)[i, reverse_sorter[:, i]]

    # For each sample, construct an array of the training responses used for prediction.
    s = [np.concatenate([np.repeat(y_train[i[0]], i[1]) for i in prox]) for prox in proximities]

    # Apply the user-specified function for each sample. Must return a numeric vector.
    y_out = np.array([what(s_i) for s_i in s])

    return y_out


X, y = datasets.load_diabetes(return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

reg = RandomForestQuantileRegressor().fit(X_train, y_train)

# Define a user-specified function; here we randomly sample 100 values with replacement.
func = lambda x: np.random.choice(x, size=100)

# Output array with the user-specified function applied to each sample's empirical distribution.
y_out = predict(reg, X_test, what=func)

print(np.std(y_out, axis=1))  # take the standard deviation of the output values
```

I believe this should do what you're looking for. Feel free to follow up if otherwise!

**Comment by jmaddalena** [comment]
Thanks so much for your detailed and helpful response. This does seem to be exactly what I need. I will say though that I did both:
```
y_out = predict(reg, X, what=lambda x: np.random.choice(x, size=10000))
```
and:
```
stdevs_empirical = predict(reg, X, what=lambda x: np.std(x))
```

And they gave essentially the same results so it appears that, at least for my use case, the resampling is not necessary. It is unclear to me why it is recommended in the documentation for ranger. 

I would suggest that you include this in the documentation somewhere because I do believe it is a common use case outside of quantiles. Thanks again!

**Comment by reidjohnson** [comment]
Great to hear. You're right that it should also work if you pass in the function of interest directly.

As for why ranger recommends resampling, I suspect it could be to avoid a ragged array, perhaps due to implementation details, and/or because there is better theoretical justification for resampling from the empirical distributions rather than calculating statistics from them directly.

And I appreciate the suggestion regarding the documentation! I can see that this may be a common use case and will work to update the documentation and/or the examples accordingly.
