### ISSUE TITLE
Add compatibility with Shap Tree Explainer

### ISSUE THREAD

**Issue by farooo2** [zillow/quantile-forest#55]
Would be great to make this library compatible with Shap Tree Explainer (https://shap-lrjball.readthedocs.io/en/latest/generated/shap.TreeExplainer.html).
This shouldn't be difficult to do considering the fact that it works with Random Forest Regressor offered by sklearn.

**Comment by reidjohnson** [comment]
@farooo2 Thanks for the issue. The QRF estimators in this package aren't currently compatible with the Tree SHAP explainer due to a strict check class check. This check currently only allows `sklearn.ensemble.RandomForestRegressor`, `sklearn.ensemble.forest.RandomForestRegressor`, and `econml.grf._base_grf.BaseGRF`.

Given how SHAP validates the model input for the Tree SHAP explainer, this issue likely falls under the scope of the SHAP project. A practical solution would be to raise an issue with the SHAP project maintainers, suggesting that they include `quantile_forest.ExtraTreesQuantileRegressor` and `quantile_forest.RandomForestQuantileRegressor` in the list of safe model instances.

In the meantime, a workaround is possible. The QRF estimators in this package fit the same estimators as a standard scikit-learn RF. So you can create a new `RandomForestRegressor` instance and populate it with the fitted estimators from a QRF. You can then use this RF instance to extract SHAP values. The resulting explanations should be identical to those produced directly from the QRF. Here's an example:

```python
import shap
from quantile_forest import RandomForestQuantileRegressor
from sklearn import datasets
from sklearn.ensemble import RandomForestRegressor
from sklearn.model_selection import train_test_split

X, y = datasets.fetch_california_housing(as_frame=True, return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=100, random_state=0)

# Train the QRF.
qrf = RandomForestQuantileRegressor(random_state=0)
qrf.fit(X_train, y_train)

# Set the RF estimators with the fitted QRF ones.
rf = RandomForestRegressor(random_state=0)
rf.estimators_ = qrf.estimators_

# Use Tree SHAP to generate explanations.
explainer = shap.TreeExplainer(rf, X_test)
shap_values = explainer(X_test, check_additivity=False)
shap.plots.waterfall(shap_values[0])
```

![treeshap_ex1](https://github.com/zillow/quantile-forest/assets/4712548/c4d5162b-113b-4b97-8d11-60cdd649ae73)

**Comment by farooo2** [comment]
This is very helpful! 
I will raise an issue with SHAP project and use what you have shared with me for the time being (very neat solution, I think this would help a lot of people using this library)
Thanks a ton @reidjohnson!

**Comment by reidjohnson** [comment]
Thanks for opening an issue with the SHAP project! Following up here after some further investigation.

While the workaround mentioned above should work for obtaining the SHAP values, because it leverages the standard RF model it may not reflect the correct QRF output when quantiles are used (i.e., _f_(_x_) and _E_[_f_(_x_)] calculated by SHAP may not match the actual values). The current implementation of Tree SHAP also doesn't appear to easily support tree models like QRF, where the quantile outputs are used dynamically at inference time instead of during training time. So there would likely be additional changes required to properly support QRFs.

That said, here's a workaround that more accurately reflects the QRF outputs, in particular with quantiles. Note that while the the feature importance values don't change, the quantile does affect the start and end output values (_E_[_f_(_x_)] and _f_(_x_)):

```python
import numpy as np
import shap
from quantile_forest import RandomForestQuantileRegressor
from sklearn import datasets
from sklearn.model_selection import train_test_split


def get_shap_values(qrf, X, quantile=0.5, **kwargs):
    # Define a custom tree model.
    model = {
        "objective": qrf.criterion,
        "tree_output": "raw_value",
        "trees": [e.tree_ for e in qrf.estimators_],
    }

    # Use Tree SHAP to generate explanations.
    explainer = shap.TreeExplainer(model, X)

    qrf_pred = qrf.predict(X.to_numpy(), quantiles=quantile, **kwargs)
    rf_pred = qrf.predict(X.to_numpy(), quantiles="mean", aggregate_leaves_first=False)

    scaling = 1.0 / len(qrf.estimators_)  # scale factor based on the number of estimators
    base_offset = qrf_pred - rf_pred  # difference between the QRF and RF (baseline) predictions

    # Adjust the tree model values.
    explainer.model.values *= scaling  # multiply based on the scaling

    # Adjust the explainer expected value.
    explainer.expected_value *= scaling  # multiply based on the scaling
    explainer.expected_value = np.tile(explainer.expected_value, len(X))  # tile to length of X
    explainer.expected_value += np.array(base_offset)  # adjust based on the quantile

    shap_values = explainer(X, check_additivity=False)
    shap_values.base_values = np.diag(shap_values.base_values)

    return shap_values


def get_shap_value_by_index(shap_values, index):
    shap_values_i = shap_values[index]
    shap_values_i.base_values = shap_values.base_values[index]
    return shap_values_i


X, y = datasets.fetch_california_housing(as_frame=True, return_X_y=True)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=100, random_state=0)

qrf = RandomForestQuantileRegressor(random_state=0)
qrf.fit(X_train, y_train)

shap_values = get_shap_values(qrf, X_test, quantile=0.5)
shap.plots.waterfall(get_shap_value_by_index(shap_values, 0))
```

![Figure_1](https://github.com/zillow/quantile-forest/assets/4712548/2d14f291-be3d-4dca-9dbe-5c0f74555286)
