### ISSUE TITLE
`ExtraTreesQuantileRegressor` doesn't reproduce results of `ExtraTreesRegressor`

### ISSUE THREAD

**Issue by t-reents** [zillow/quantile-forest#76]
Dear @reidjohnson

first of all, thanks for providing this great repository. 

As indicated in the title, I'm encountering a problem where I can't reproduce the results of a sklearn `ExtraTreesRegressor` when using the `ExtraTreesQuantileRegressor` model (I'm observing a similar behavior when using the corresponding random forest models).

I'm following the example at https://zillow.github.io/quantile-forest/user_guide/fit_predict.html#random-forest-predictions and have also set `max_samples_leaf = None` in case of the ETQR. Moreover, I can reproduce the example, so everything works fine for that dataset.
However, when using my own dataset, I don't obtain matching results if I specify `max_depth` and/or `min_samples_split` (in the specific case I'm using `max_depth = 8` and `min_samples_split = 0.02`) when initializing the models.

Is this a known problem? If yes, what is happening in such cases, and how can it be solved? Since I obtained these hyperparameters after an optimization of the  `ExtraTreesRegressor`, I'd need to be able to use the same for the `ExtraTreesQuantileRegressor` to actually compare consistent results.

Thanks in advance!

**Comment by reidjohnson** [comment]
@t-reents: Thanks for reporting the issue! I'm not aware of cases where this would happen and I've not been able to reproduce it with the regression datasets provided in scikit-learn. Would you happen to be able to provide the code for a minimally reproducible example? I'd be very interested in identifying the source and scope of this issue.

**Comment by t-reents** [comment]
Thanks for your quick reply! I forked the repo and created a folder with the required data and a MWE (minimal working example): https://github.com/t-reents/quantile-forest/tree/issue_76_reproduce_sklearn/analyze_qrf_issue

Some of the columns/features contain a significant number of 0-values. Those were added to replace `NaN` values. I initially thought that this might be the issue, but after removing those columns, the issue still persists. 

Please let me know if I can further support.

**Comment by reidjohnson** [comment]
@t-reents: Thanks for the comprehensive example. I was able to use it to identify the source of this issue.

It turns out that the `absolute_error` criterion is relatively unique for the scikit-learn forest estimators in that it aggregates estimates of the median instead of the mean. In cases of trees with many samples per leaf, such as with certain settings of `max_depth` or `min_samples_split`, doing this aggregation properly with the quantile forest implementation required a fix.

You should find that your example now works if you set `quantiles=0.5` in the most recent version of the package, 1.3.9. Feel free to reopen the issue if you identify any further cases.
