### ISSUE TITLE
CVE-2024-5206 - Scikit-learn minimum version

### ISSUE THREAD

**Issue by brentonmallen1** [zillow/quantile-forest#91]
Currently, the minimum version for scikit-learn is set to 1.0, and it would need to be set to 1.5 in order to mitigate the vulnerability in [CVE-2024-5206](https://github.com/advisories/GHSA-jw8x-6495-233v).  Latest version of sklearn is [1.5.2](https://github.com/scikit-learn/scikit-learn/releases/tag/1.5.2) which no longer supports python 3.8 but that's [nigh end of life](https://devguide.python.org/versions/).

**Comment by brentonmallen1** [comment]
If it's as 'simple' as updating the minimum version in the [min-dependencies](https://github.com/zillow/quantile-forest/blob/main/quantile_forest/_min_dependencies.py#L9) and [pyproject.toml](https://github.com/zillow/quantile-forest/blob/main/pyproject.toml#L9),  and removing py3.8 references (or if there's more to consider and someone can point me in the direction of what else that might be) I'd be happy to make a PR.

**Comment by reidjohnson** [comment]
Thanks for raising this issue -- a PR is very welcome!

You're spot on about what's needed to update the minimum version and removing Python 3.8 references/support.

The one additional task would be to clean up backward-compatible code that supported older versions of scikit-learn. There are a number of details here, so I'd be happy to lend a hand as well. But this includes the documentation ([here](https://github.com/zillow/quantile-forest/blob/72f83154e84df0463473c5603deaed6db06934ab/docs/getting_started/installation.rst)), the model parameters ([here](https://github.com/zillow/quantile-forest/blob/72f83154e84df0463473c5603deaed6db06934ab/quantile_forest/_quantile_forest.py#L97-L99), [here](https://github.com/zillow/quantile-forest/blob/72f83154e84df0463473c5603deaed6db06934ab/quantile_forest/_quantile_forest.py#L1360-L1361), and [here](https://github.com/zillow/quantile-forest/blob/72f83154e84df0463473c5603deaed6db06934ab/quantile_forest/_quantile_forest.py#L1693-L1694)), the docstrings ([here](https://github.com/zillow/quantile-forest/blob/72f83154e84df0463473c5603deaed6db06934ab/quantile_forest/_quantile_forest.py#L1130C12-L1131) and [here](https://github.com/zillow/quantile-forest/blob/72f83154e84df0463473c5603deaed6db06934ab/quantile_forest/_quantile_forest.py#L1474-L1475)), the parse version try-except ([here](https://github.com/zillow/quantile-forest/blob/72f83154e84df0463473c5603deaed6db06934ab/quantile_forest/_quantile_forest.py#L42-L45)), and the parameter validation check ([here](https://github.com/zillow/quantile-forest/blob/72f83154e84df0463473c5603deaed6db06934ab/quantile_forest/_quantile_forest.py#L47C1-L51)) along with the corresponding conditionals, since it should now always import successfully.

**Comment by brentonmallen1** [comment]
I opened a [PR](https://github.com/zillow/quantile-forest/pull/92)

A couple of things I came across:

- I didn't see a dev environment, so I wound up just creating a local conda environment with the min dependencies and pytest. Otherwise I couldn't run the`python setup.py build_ext --inplace` step in the build.  Not sure If I missed a step that I should/could document for a dev environment
-  I didn't make any changes with the sklearn utils stuff because they either seemed like they were still needed to me or, in the case of the fixes file, it seemed needed until the scipy and numpy min versions were raised. I didn't make those changes in favor of keeping this PR minimal as mentioned in the contribution file

Let me know what your thoughts are

**Comment by reidjohnson** [comment]
Ah, thanks for the note on the build issues. One problem here is that CONTRIBUTING.md is out-of-date; I have been keeping the development instructions updated in the documentation [here](https://zillow.github.io/quantile-forest/getting_started/developers.html). That said, you may still be right that including additional instructions for setting up a dev environment would be helpful. Thanks for pointing out the issues here, the instructions should be updated and consolidated.

**Comment by brentonmallen1** [comment]
no worries.  Your test coverage is inspirational
